### ISSUE TITLE
How to launch the annotot server ?

### ISSUE THREAD

**Issue by dbeniamine** [mejackreed/annotot#15]
Hi,

I am trying to start an annotot server to integrate with a mirador project, but I am a bit lost ...

This is what I am doing : 

```
git clone https://github.com/PenguinParadigm/annotot
docker run --rm -it -v $PWD/annotot:/app ruby /bin/bash
```

Then in the docker container : 

```
cd /app
bundle install
```

Which seems to work well :

```
Using annotot 0.7.0 from source at `.`
Fetching engine_cart 2.5.0
Installing engine_cart 2.5.0
Bundle complete! 6 Gemfile dependencies, 56 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

```
bundle info annotot
  * annotot (0.7.0)
        Summary: Annotot. Open annotations in Rails.
        Homepage: https://github.com/mejackreed/annotot
        Path: /app
```

But then when I try to run the server : 

```
./bin/rails server
/usr/local/bundle/gems/railties-7.0.4/lib/rails/command/actions.rb:10:in `set_application_directory!': uninitialized constant Rails::Command::Actions::APP_PATH (NameError)

        Dir.chdir(File.expand_path("../..", APP_PATH)) unless File.exist?(File.expand_path("config.ru"))
                                            ^^^^^^^^
        from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:131:in `perform'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
        from /usr/local/bundle/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
        from /usr/local/bundle/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<top (required)>'
        from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine/commands.rb:9:in `require'
        from /usr/local/bundle/gems/railties-7.0.4/lib/rails/engine/commands.rb:9:in `<top (required)>'
        from ./bin/rails:13:in `require'
        from ./bin/rails:13:in `<main>'
```

Note I have never ran a ruby application directly, what I want is to have an annotot server running inside a docker container.

Maybe I am doing this wrong but the readme is not very helpful in my case

**Comment by mejackreed** [comment]
Annotot is a Rails engine, meaning, that it is meant to be installed in an existing Ruby on Rails application. Are you installing annotot into an existing rails application?

**Comment by dbeniamine** [comment]
I thought it was usable both as a standalone rest server or in an existing app.

Is there a minimal example of an annotot application ?

**Comment by mejackreed** [comment]
There is an older version here: https://github.com/mejackreed/annotot-app

**Comment by dbeniamine** [comment]
Thanks, reading this repository, I managed to create an annotot server.

In case this can help anyone :  

+ my repository is here : https://gitlab.tetras-libre.fr/iiif/annotot-app and the image is here https://hub.docker.com/repository/docker/tetraslibre/annotot-app
+ **I have not tested it extensively yet**, but if you run : `docker run --rm -it -p 3000:3000 tetraslibre/annotot-app`, you can see annotation routes on `/annotation` 

![image](https://user-images.githubusercontent.com/2989133/198050909-91270f8e-d2b3-4361-a5c9-cb0b1f3f38ce.png)
